### PR TITLE
use custom fields

### PR DESCRIPTION
**Pull request by alexturkin**
depends on https://github.com/alertlogic/al-collector-js/pull/3 

### Problem

We need to support collectors with custom fields for reg request. In particular, CWL

### Solution
https://github.com/alertlogic/al-collector-js/pull/3 + change CWE collector to use new interface

### CODE REVIEW

**Comment by alexturkin** [comment]
it's failed because https://github.com/alertlogic/al-collector-js/pull/3 is not merged

**Comment by kkuzmin** [comment]
@alexturkin dependency merged. could you please fix the tests?

**Comment by alexturkin** [comment]
test it

**Comment by alexturkin** [comment]
@kkuzmin fixed

**Pull request merged**
